version: "3"
services:
  app:
    build: ./infra/php
    container_name: "php"
    volumes:
      - ./src:/var/www


  webserver:
    image: nginx:1.20-alpine
    container_name: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    
  

